# Generated by Django 3.0.5 on 2020-08-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_reporter_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reporters/'),
        ),
    ]
