# Generated by Django 3.0.5 on 2020-08-23 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20200822_2224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reporter',
            old_name='user',
            new_name='reporter',
        ),
    ]
