# Generated by Django 3.0.5 on 2020-08-23 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20200822_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='reporter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='news.Reporter'),
        ),
    ]
