# Generated by Django 3.0.5 on 2020-08-24 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_auto_20200823_1701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='reporter',
            new_name='by',
        ),
    ]
