# Generated by Django 3.0.5 on 2020-08-24 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_auto_20200823_1943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='by',
            new_name='article_reporter',
        ),
    ]
