# Generated by Django 3.0.5 on 2020-08-25 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_auto_20200824_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='article',
            new_name='comment_article',
        ),
    ]
