# Generated by Django 3.0.5 on 2020-08-25 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0022_auto_20200824_2153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_article',
            new_name='article_id',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='body',
        ),
    ]
